apiVersion: v1
kind: Service
metadata:
  name: pikachus-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.224.100.84
  selector:
    app: helloworld
  ports:
    - port: 80
      targetPort: 3000
